### ISSUE TITLE
start-local-athenz.sh does not work when using nerdctl

### ISSUE THREAD

**Issue by hiragi-gkuth** [AthenZ/athenz#2310]
Running 'start-local-athenz.sh' with nerdctl will result in the following error.

```
# Setting an alias for the docker command to nerdctl
~ ❯❯❯ ./start-local-athenz.sh
# generate self-signed certificates
docker run --rm -t -v "/Users/me/ghq/github.com/athenz/athenz:/athenz" --user "504:20" athenz/athenz-setup-env sh /athenz/docker/setup-scripts/self-signed-certificates.sh
panic: provided file is not a console

goroutine 1 [running]:
github.com/containerd/console.Current()
        /go/pkg/mod/github.com/containerd/console@v1.0.3/console.go:77 +0xa5
main.runAction(0xc000004900, {0xc000564510, 0x3, 0x9})
        /go/src/github.com/containerd/nerdctl/cmd/nerdctl/container_run.go:349 +0x6c5
github.com/spf13/cobra.(*Command).execute(0xc000004900, {0xc00003e0d0, 0x9, 0x9})
        /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000004300)
        /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.xmain()
        /go/src/github.com/containerd/nerdctl/cmd/nerdctl/main.go:136 +0x9f
main.main()
        /go/src/github.com/containerd/nerdctl/cmd/nerdctl/main.go:119 +0x19
Error: exit status 2
make: *** [Makefile:64: deploy-local] Error 1
```

I have found that removing the '-t' option from the docker command in docker/Makefile works fine.

before
```
docker run --rm -t -v "$(BASE_DIR):/athenz" --user "$(shell id -u):$(shell id -g)" athenz/ath
    enz-setup-env sh /athenz/docker/setup-scripts/self-signed-certificates.sh
```

after
```
docker run --rm -v "$(BASE_DIR):/athenz" --user "$(shell id -u):$(shell id -g)" athenz/ath
    enz-setup-env sh /athenz/docker/setup-scripts/self-signed-certificates.sh
```

I think [this issue](https://github.com/containerd/nerdctl/issues/560) is relevant. but it is marked as resolved, so I've asking this question to seek a solution to this problem.

Separately, as a workaround, I am considering making it possible to run without the "-t" option. Do you have any concerns about this approach? Also, if you have any other suggestions, please let me know.

**Comment by hiragi-gkuth** [comment]
I noticed that this problem occurs only when deploying local Athenz via 'start-local-athenz.sh'. On the other hand, when trying to run 'make deploy-local', some issues that include nerdctl error were not relevant.
so I close this issue.

However, several issues are still remaining, so I will submit a Pull-Request."
